import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

import { Navbar } from "@app/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fardin Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-100 to-red-100 px-4 sm:px-8 lg:px-16 xl:px-20 overflow-x-hidden relative">
          <nav className="h-20">
            <Navbar />
          </nav>
          <main className="h-[calc(100vh-5rem)]">{children}</main>
        </div>
      </body>
    </html>
  );
}
